# Find BGFX
if (NOT DEFINED BGFX_INCLUDE_DIR OR NOT DEFINED BGFX_LIBRARY_DEBUG OR NOT DEFINED BGFX_LIBRARY_RELEASE)
	message(FATAL_ERROR "Please set BGFX_INCLUDE_DIR, BGFX_LIBRARY_DEBUG and BGFX_LIBRARY_RELEASE")
else()
	message(STATUS "Found BGFX ${BGFX_INCLUDE_DIR} (debug: ${BGFX_LIBRARY_DEBUG} optimized: ${BGFX_LIBRARY_RELEASE})")
endif()

# Find BIMG
if (NOT DEFINED BIMG_INCLUDE_DIR OR NOT DEFINED BIMG_LIBRARY_DEBUG OR NOT DEFINED BIMG_LIBRARY_RELEASE)
	message(FATAL_ERROR "Please set BIMG_INCLUDE_DIR, BIMG_LIBRARY_DEBUG and BIMG_LIBRARY_RELEASE")
else()
	message(STATUS "Found BIMG ${BIMG_INCLUDE_DIR} (debug: ${BIMG_LIBRARY_DEBUG} optimized: ${BIMG_LIBRARY_RELEASE})")
endif()

if (NOT DEFINED BIMG_DECODE_LIBRARY_DEBUG OR NOT DEFINED BIMG_DECODE_LIBRARY_RELEASE)
	message(FATAL_ERROR "Please set BIMG_DECODE_LIBRARY_DEBUG and BIMG_DECODE_LIBRARY_RELEASE")
else()
	message(STATUS "Found BIMG Decode (debug: ${BIMG_DECODE_LIBRARY_DEBUG} optimized: ${BIMG_DECODE_LIBRARY_RELEASE})")
endif()

# Find BX
if (NOT DEFINED BX_INCLUDE_DIR OR NOT DEFINED BX_LIBRARY_DEBUG OR NOT DEFINED BX_LIBRARY_RELEASE)
	message(FATAL_ERROR "Please set BGFX_INCLUDE_DIR, BGFX_LIBRARY_DEBUG and BX_LIBRARY_RELEASE")
else()
	message(STATUS "Found BX ${BX_INCLUDE_DIR} (debug: ${BX_LIBRARY_DEBUG} optimized: ${BX_LIBRARY_RELEASE})")
endif()
